#!/bin/bash

# SPDX-License-Identifier: GPL-3.0
#
# Copyright (C) 2025 KaliAssistant
# Author: KaliAssistant
#
# This file is part of the Lichee-Jack project and is licensed under the GNU
# General Public License v3.0 or later.

cat << 'EOF'


                      ``..`                           
                    `.--.`                            
                   `--.                               
                   --`                                
                  `--             `----------------.  
          ````...`.-.``.``        .-K@mQWRQ$@G@$Q@,-  
       `.,!!~?]j{\!_;\szi!-..`    .-O@'^^^^^^^^^G@,-  
     ``-_222222x__?22j;_|2{nl,.`  .-O@'|||||||||G@,-  
   `-_7]j/,r222222y2222s/2j\vc+_-`.-O@c|||||||||W@,-  
   `-v222|?22yj22222y22222y|'|22+---wQQQQQQQQQQQQQ,-  
  .,^zj|i222s'+2222y!,\22(/yv]22_--''''''''''''''''--`
 .'j22r'n222zr2222222ii22s-|2jn2v-'j222222222222222^-`
 `-+22}/22j2222y}22222222j|u2l-(j-'y222222222222222^-`
`-!nyr(22('z222^,22222\^z2222{!zj-'y222222222222222^-`
`-/2j,!y2x_/222  LICHEE  22/s222j'-;^^^^  JACK  ^^^,-`
 `'^2jz2222222222222222nj2y!_2uY2+-,||||||||||||||^-- 
 `-/222n^n222_+y222j_l2222Y+x2|-]v--'''''''''''''''-` 
 `-;]22j__c22s^|22]!,s22n\y22{!||,..'|///(/(/////_-`  
  `.-|222uy22222222n222z^'n22222_-  --~_________'-`   
   `-^y222y~+zy2u72y222((uji'z{|'.  `-,++++++++!-`    
    `.'_^22}?+n2n;__722222r^cr-.`     ``.-_!-.```     
       `'|uyxj22222222jr|2v(r'.  V1.0   `-_u!-`       
        `...-_vv~l22y;_rY?--``       `.'=x_-`         
             ``..,r|+_',''^_'..`...',;/v^'`           
                  ````  `.,!|\\/////=!,.`             
                           `````..````                

                      LICHEE-JACK V1.0
                      by KaliAssistant


EOF
