#!/bin/bash

export LOG="logger -t LicheeJack [*]"
export LOG_ERR="logger -t LicheeJack -p 3 [!]"


MODE="DEBUG"
MODSWITCH_POS=$(/usr/bin/SWITCH)

prepare_usb_gadgat() {
    echo "device" > /proc/cviusb/otg_role
}

enter_payload1_mode() {
    $LOG "Entering PAYLOAD1 mode"
    MODE="PAYLOAD1"
    /usr/bin/LED -c 00FFFF -lds 100000

    ip link set end0 down
    macchanger -r end0
    ip link set end0 up

    USBMODE STOP_ALL
    systemctl stop ssh.service

    /usr/bin/RUN MOD1

    enter_idle_mode

}


enter_payload2_mode() {
    $LOG "Entering PAYLOAD2 mode"
    MODE="PAYLOAD2"
    /usr/bin/LED -c FF00FF -lds 100000

    ip link set end0 down
    macchanger -r end0
    ip link set end0 up

    USBMODE STOP_ALL
    systemctl stop ssh.service

    /usr/bin/RUN MOD2

    enter_idle_mode

}


enter_debug_mode() {
    $LOG "Entering DEBUG mode"
    MODE="DEBUG"
    /usr/bin/LED -c 0000FF -lds 1000000

    prepare_usb_gadgat

    USBMODE DEBUG
    USBNET SETIP 10.42.0.1/24
    UDHCPCTL START debug-usb0
    systemctl start ssh.service

    sleep 1
    enter_idle_mode
}


enter_idle_mode() {
    $LOG "Entering IDLE mode"
    while true
    do
        MODSWITCH_POS=$(/usr/bin/SWITCH)
        case $MODSWITCH_POS in
            "switch2")
                if [ "$MODE" != "PAYLOAD2" ]; then
                    enter_payload2_mode
                fi
                ;;
            "switch1")
                if [ "$MODE" != "PAYLOAD1" ]; then
                    enter_payload1_mode
                fi
                ;;
            *)
                if [ "$MODE" != "DEBUG" ]; then
                    enter_debug_mode
                fi
                ;;
        esac
        sleep 2
    done
}

run() {
    case $MODSWITCH_POS in
        "switch2")
            enter_payload2_mode 
            ;;
        "switch1")
            enter_payload1_mode
            ;;
        *)
            enter_debug_mode
            ;;
    esac
}

run > /dev/null 2>&1
