#!/bin/bash

ARG=$1

LOG="logger -t LicheeJack [*]"
LOG_ERR="logger -t LicheeJack -p 3 [!]"
$LOG "Prepping PAYLOAD environment..."

pre_check() {
    if [ ! -d /root/udisk.d/payloads/mod1.d ] || [ ! -d /root/udisk.d/payloads/mod2.d ]; then
        $LOG_ERR "Cannot find payloads directory! stop."
        /usr/bin/LED -c FF0000 -lbs 500000
        exit 1
    fi

    if [ ! -d /root/udisk.d/loot ]; then
        $LOG "LOOT directory not found. creating /root/udisk.d/loot ... "
        mkdir -p /root/udisk.d/loot
    fi
}

case $ARG in
    "MOD1")
          pre_check
          payload=$(find "/root/udisk.d/payloads/mod1.d"/payload* 2>/dev/null | tail -n1)
          case $(basename "${payload}") in
              "payload.py")
                  $LOG "Running payload \`${payload}\` (python3)"
                  python3 "${payload}" > /dev/null 2>&1
                  ;;
              "payload" | "payload.sh" | "payload.txt")
                  sed -i 's/\r//g' "${payload}"
                  $LOG "Running payload \`${payload}\` (bash)"
                  bash -C "${payload}" > /dev/null 2>&1
                  ;;
              *)
                  $LOG_ERR "Cannot find any executable payloads in /root/udisk.d/payloads/mod1.d !"
                  /usr/bin/LED -c FF0000 -lbs 500000
                  exit 1
                  ;;
          esac
          ;;
    "MOD2")
          pre_check
          payload=$(find "/root/udisk.d/payloads/mod2.d"/payload* 2>/dev/null | tail -n1)
          case $(basename "${payload}") in
              "payload.py")
                  $LOG "Running payload \`${payload}\` (python3)"
                  python3 "${payload}" > /dev/null 2>&1
                  ;;
              "payload" | "payload.sh" | "payload.txt")
                  sed -i 's/\r//g' "${payload}"
                  $LOG "Running payload \`${payload}\` (bash)"
                  bash -C "${payload}" > /dev/null 2>&1
                  ;;
              *)
                  $LOG_ERR "Cannot find any executable payloads in /root/udisk.d/payloads/mod2.d !"
                  /usr/bin/LED -c FF0000 -lbs 500000
                  exit 1
                  ;;
          esac
          ;;
    *)
          $LOG "Specified payload mode!"
          if [ ! -e $ARG ]; then
              $LOG_ERR "The specified payload \`${ARG}\` does not exist ! stop."
              /usr/bin/LED -c FF0000 -lbs 500000
              exit 1
          fi
          $LOG "Running specified payload \`${ARG}\` (executable file)"
          bash -C "${ARG}" > /dev/null 2>&1
          ;;
esac
